language: objective-c
osx_image: xcode9.3

before_install:
- gem install cocoapods -v '1.5.3'
- pod repo update

xcode_workspace: LeadKit.xcworkspace
xcode_scheme: LeadKit iOSTests
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 6s
