
language: objective-c
osx_image: xcode9.4

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - xcodebuild test -enableCodeCoverage YES -workspace LeadKit.xcworkspace -scheme 'LeadKit iOS' -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator | xcpretty -c
    - xcodebuild test -enableCodeCoverage YES -workspace LeadKit.xcworkspace -scheme 'LeadKit iOS Extensions' -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator | xcpretty -c
    - xcodebuild test -enableCodeCoverage YES -workspace LeadKit.xcworkspace -scheme 'LeadKit tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 4K' -sdk appletvsimulator | xcpretty -c
    - xcodebuild test -enableCodeCoverage YES -workspace LeadKit.xcworkspace -scheme 'LeadKit watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch' -sdk watchsimulator | xcpretty -c

after_success:
    #
